/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package HCI;

import control.exceptions.NonexistentEntityException;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityNotFoundException;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;

/**
 * @author Joynal Abedin 14-Jul-2013
 */
public class EditCarePackDocsFrame extends javax.swing.JFrame {

    /**
     * Creates new form EditCarePackDocsFrame
     */
    public EditCarePackDocsFrame() {
        initComponents();
        
        setTitle(
                "Simple Legal System                     View or Edit or Update a carePack doc here");
        this.setIconImage(new ImageIcon("legal.gif").getImage());
        // centre the user interface on the screen
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((screenSize.width - getWidth()) / 2,
                (screenSize.height - getHeight()) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel5 = new javax.swing.JLabel();
        txtFolderID = new javax.swing.JTextField();
        FindjButton = new javax.swing.JButton();
        EditSelectedFileViewDoc2 = new javax.swing.JTextField();
        EditLocate5 = new javax.swing.JButton();
        EditOpenFilejButton2 = new javax.swing.JButton();
        EditMimeType2 = new javax.swing.JTextField();
        EditMimeType5 = new javax.swing.JTextField();
        EditLocate1 = new javax.swing.JButton();
        EditOpenFilejButton5 = new javax.swing.JButton();
        EditLocate2 = new javax.swing.JButton();
        LastNamejLabel = new javax.swing.JLabel();
        EditMimeType1 = new javax.swing.JTextField();
        EditOpenFilejButton1 = new javax.swing.JButton();
        FirstNamejLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        FirstNamejTextField = new javax.swing.JTextField();
        EditSelectedFileViewDoc1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FolderNamejTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        LastNamejTextField = new javax.swing.JTextField();
        EditSelectedFileViewDoc3 = new javax.swing.JTextField();
        EditMimeType3 = new javax.swing.JTextField();
        EditOpenFilejButton3 = new javax.swing.JButton();
        EditLocate3 = new javax.swing.JButton();
        EditLocate4 = new javax.swing.JButton();
        EditOpenFilejButton4 = new javax.swing.JButton();
        EditMimeType4 = new javax.swing.JTextField();
        EditSelectedFileViewDoc4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        EditSelectedFileViewDoc5 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButtonBack2Main = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Enter a CarePack No");

        FindjButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FindjButton.setText("Find");
        FindjButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                FindjButtonActionPerformed(evt);
            }
        });

        EditLocate5.setText("Locate");
        EditLocate5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditLocate5ActionPerformed(evt);
            }
        });

        EditOpenFilejButton2.setText("OpenFile");
        EditOpenFilejButton2.setActionCommand("");
        EditOpenFilejButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditOpenFilejButton2ActionPerformed(evt);
            }
        });

        EditMimeType2.setEditable(false);

        EditMimeType5.setEditable(false);

        EditLocate1.setText("Locate");
        EditLocate1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditLocate1ActionPerformed(evt);
            }
        });

        EditOpenFilejButton5.setText("OpenFile");
        EditOpenFilejButton5.setActionCommand("");
        EditOpenFilejButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditOpenFilejButton5ActionPerformed(evt);
            }
        });

        EditLocate2.setText("Locate");
        EditLocate2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditLocate2ActionPerformed(evt);
            }
        });

        LastNamejLabel.setText("Last Name");

        EditMimeType1.setEditable(false);

        EditOpenFilejButton1.setText("OpenFile");
        EditOpenFilejButton1.setActionCommand("");
        EditOpenFilejButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditOpenFilejButton1ActionPerformed(evt);
            }
        });

        FirstNamejLabel.setText("First Name");

        jLabel19.setText("Edit Doc 1");

        FirstNamejTextField.setEditable(false);
        FirstNamejTextField.setToolTipText("Enter a first name");
        FirstNamejTextField.setName("FirstName"); // NOI18N
        FirstNamejTextField.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel16.setText("Edit Doc 3");

        jLabel6.setText("Edit Doc 2");

        FolderNamejTextField1.setEditable(false);
        FolderNamejTextField1.setToolTipText("Enter a folder name");

        jLabel1.setText("Enter folder name");

        LastNamejTextField.setEditable(false);

        EditMimeType3.setEditable(false);

        EditOpenFilejButton3.setText("OpenFile");
        EditOpenFilejButton3.setActionCommand("");
        EditOpenFilejButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditOpenFilejButton3ActionPerformed(evt);
            }
        });

        EditLocate3.setText("Locate");
        EditLocate3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditLocate3ActionPerformed(evt);
            }
        });

        EditLocate4.setText("Lcoate");
        EditLocate4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditLocate4ActionPerformed(evt);
            }
        });

        EditOpenFilejButton4.setText("OpenFile");
        EditOpenFilejButton4.setActionCommand("");
        EditOpenFilejButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditOpenFilejButton4ActionPerformed(evt);
            }
        });

        EditMimeType4.setEditable(false);

        jLabel17.setText("Edit Doc 4");

        jLabel18.setText("Edit Doc 5");

        jButtonBack2Main.setText("Back to Main");
        jButtonBack2Main.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonBack2MainActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update and Save");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButtonBack2Main)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1))
                    .addComponent(LastNamejLabel)
                    .addComponent(FirstNamejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FirstNamejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(LastNamejTextField)
                    .addComponent(FolderNamejTextField1))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(9, 9, 9)
                                .addComponent(EditSelectedFileViewDoc4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EditMimeType4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(9, 9, 9)
                                .addComponent(EditSelectedFileViewDoc5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EditMimeType5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditOpenFilejButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EditOpenFilejButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(EditLocate5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EditLocate4, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(4, 4, 4)
                                        .addComponent(EditSelectedFileViewDoc1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(EditMimeType1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(4, 4, 4)
                                                .addComponent(EditSelectedFileViewDoc2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(EditSelectedFileViewDoc3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EditMimeType3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EditMimeType2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel16))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(EditOpenFilejButton1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(EditOpenFilejButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EditOpenFilejButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditLocate3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(EditLocate2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EditLocate1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)
                        .addComponent(txtFolderID, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(FindjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonUpdate)
                        .addGap(122, 122, 122))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtFolderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(FindjButton))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EditOpenFilejButton1)
                        .addGap(3, 3, 3)
                        .addComponent(EditOpenFilejButton2)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EditOpenFilejButton3)
                            .addComponent(EditLocate3)
                            .addComponent(EditMimeType3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EditMimeType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EditLocate1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(EditSelectedFileViewDoc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EditMimeType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(FirstNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(FirstNamejLabel))
                                                    .addComponent(EditSelectedFileViewDoc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EditLocate2))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(FolderNamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(EditSelectedFileViewDoc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LastNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LastNamejLabel))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EditMimeType4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EditOpenFilejButton4)
                        .addComponent(EditLocate4)
                        .addComponent(EditSelectedFileViewDoc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EditMimeType5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EditOpenFilejButton5)
                        .addComponent(EditLocate5)
                        .addComponent(EditSelectedFileViewDoc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addComponent(jButtonUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jButtonBack2Main)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FindjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindjButtonActionPerformed
        int id = Integer.parseInt(txtFolderID.getText());

        try
        {
            findbyId(id);
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_FindjButtonActionPerformed

    private void EditLocate5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditLocate5ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        try {
            EditSelectedFileViewDoc5.setText(chooser.getSelectedFile().toString());
            EditMimeType5.setText(EditSelectedFileViewDoc5.getText().substring(EditSelectedFileViewDoc5.getText().lastIndexOf('.')+1));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_EditLocate5ActionPerformed


public void writeFile(File file, byte[] data) throws IOException
 {
   OutputStream fo = new FileOutputStream(file);
   fo.write(data);
   fo.flush();
   fo.close();
 }    
          
    private void EditOpenFilejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditOpenFilejButton2ActionPerformed
//        int id = Integer.parseInt(txtFolderID.getText());
//        EntityManagerFactory emf = Persistence.createEntityManagerFactory("slSystemPU");
//        EntityManager em = emf.createEntityManager();
//
//        Clientfolder clientfolder;
//
//        clientfolder = em.getReference(Clientfolder.class, id);
//        //clientfolder.getDoc1();
//
//        JFileChooser fr = new JFileChooser();
//        FileSystemView fw = fr.getFileSystemView();
//        System.out.println(fw.getDefaultDirectory());
//        String FilePathWithName=fw.getDefaultDirectory() + "\\client_" + id + "_02." + clientfolder.getMime2();
//
//        File outfile = null;
//        outfile = new File(FilePathWithName);
//
//        try
//        {
//            writeFile(outfile, clientfolder.getDoc2());
//        }
//        catch (IOException e)
//        {
//            System.out.println(e.getMessage());
//        }
//        try {
//            Runtime rt = Runtime.getRuntime();
//            rt.exec("cmd /c start " + ResolveWhiteSpace(FilePathWithName));
//
//        } catch (Exception e) {
//            System.out.println("Error opening file: " + e.getMessage());
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_EditOpenFilejButton2ActionPerformed

    private void EditLocate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditLocate1ActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        try {
            EditSelectedFileViewDoc1.setText(chooser.getSelectedFile().toString());
            EditMimeType1.setText(EditSelectedFileViewDoc1.getText().substring(EditSelectedFileViewDoc1.getText().lastIndexOf('.')+1));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_EditLocate1ActionPerformed

    private void EditOpenFilejButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditOpenFilejButton5ActionPerformed
//        int id = Integer.parseInt(txtFolderID.getText());
//        EntityManagerFactory emf = Persistence.createEntityManagerFactory("slSystemPU");
//        EntityManager em = emf.createEntityManager();
//
//        Clientfolder clientfolder;
//
//        clientfolder = em.getReference(Clientfolder.class, id);
//        //clientfolder.getDoc1();
//
//        JFileChooser fr = new JFileChooser();
//        FileSystemView fw = fr.getFileSystemView();
//        System.out.println(fw.getDefaultDirectory());
//        String FilePathWithName=fw.getDefaultDirectory() + "\\client_" + id + "_05." + clientfolder.getMime5();
//
//        File outfile = null;
//        outfile = new File(FilePathWithName);
//
//        try
//        {
//            writeFile(outfile, clientfolder.getDoc5());
//        }
//        catch (IOException e)
//        {
//            //Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, e);
//        }
//        try {
//            Runtime rt = Runtime.getRuntime();
//            rt.exec("cmd /c start " + ResolveWhiteSpace(FilePathWithName));
//
//        } catch (Exception e) {
//            System.out.println("Error opening file: " + e.getMessage());
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_EditOpenFilejButton5ActionPerformed

    private void EditLocate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditLocate2ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        try {
            EditSelectedFileViewDoc2.setText(chooser.getSelectedFile().toString());
            EditMimeType2.setText(EditSelectedFileViewDoc2.getText().substring(EditSelectedFileViewDoc2.getText().lastIndexOf('.')+1));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_EditLocate2ActionPerformed

    public String ResolveWhiteSpace(String FileName) {

        String FileName2 = FileName;
        for (int x = 0; x < FileName.length(); x++) {
            if (FileName.charAt(x) == ' ') {
                FileName2 = FileName.substring(0, x) + "\"" + FileName.substring(x, FileName.length()) + "\"";
                break;
            }
        }
        return FileName2;
    }
    
    private void EditOpenFilejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditOpenFilejButton1ActionPerformed
//        int id = Integer.parseInt(txtFolderID.getText());
//        EntityManagerFactory emf = Persistence.createEntityManagerFactory("slSystemPU");
//        EntityManager em = emf.createEntityManager();
//
//        Clientfolder clientfolder;
//
//        clientfolder = em.getReference(Clientfolder.class, id);
//        //clientfolder.getDoc1();
//
//        JFileChooser fr = new JFileChooser();
//        FileSystemView fw = fr.getFileSystemView();
//        System.out.println(fw.getDefaultDirectory());
//        String FilePathWithName=fw.getDefaultDirectory() + "\\client_" + id + "_01." + clientfolder.getMime1();
//
//        File outfile = null;
//        outfile = new File(FilePathWithName);
//
//        try
//        {
//            writeFile(outfile, clientfolder.getDoc1());
//        }
//        catch (IOException e)
//        {
//            System.out.println(e.getMessage());
//        }
//        try {
//            Runtime rt = Runtime.getRuntime();
//            rt.exec("cmd /c start " + ResolveWhiteSpace(FilePathWithName));
//
//        } catch (Exception e) {
//            System.out.println("Error opening file: " + e.getMessage());
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_EditOpenFilejButton1ActionPerformed

    private void EditOpenFilejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditOpenFilejButton3ActionPerformed
//        int id = Integer.parseInt(txtFolderID.getText());
//        EntityManagerFactory emf = Persistence.createEntityManagerFactory("slSystemPU");
//        EntityManager em = emf.createEntityManager();
//
//        Clientfolder clientfolder;
//
//        clientfolder = em.getReference(Clientfolder.class, id);
//        //clientfolder.getDoc1();
//
//        JFileChooser fr = new JFileChooser();
//        FileSystemView fw = fr.getFileSystemView();
//        System.out.println(fw.getDefaultDirectory());
//        String FilePathWithName=fw.getDefaultDirectory() + "\\client_" + id + "_03." + clientfolder.getMime3();
//
//        File outfile = null;
//        outfile = new File(FilePathWithName);
//
//        try
//        {
//            writeFile(outfile, clientfolder.getDoc3());
//        }
//        catch (IOException e)
//        {
//            System.out.println(e.getMessage());
//        }
//        try {
//            Runtime rt = Runtime.getRuntime();
//            rt.exec("cmd /c start " + ResolveWhiteSpace(FilePathWithName));
//
//        } catch (Exception e) {
//            System.out.println("Error opening file: " + e.getMessage());
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_EditOpenFilejButton3ActionPerformed

    private void EditLocate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditLocate3ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        try {
            EditSelectedFileViewDoc3.setText(chooser.getSelectedFile().toString());
            EditMimeType3.setText(EditSelectedFileViewDoc3.getText().substring(EditSelectedFileViewDoc3.getText().lastIndexOf('.')+1));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_EditLocate3ActionPerformed

    private void EditLocate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditLocate4ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        try {
            EditSelectedFileViewDoc4.setText(chooser.getSelectedFile().toString());
            EditMimeType4.setText(EditSelectedFileViewDoc4.getText().substring(EditSelectedFileViewDoc4.getText().lastIndexOf('.')+1));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_EditLocate4ActionPerformed

    private void EditOpenFilejButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditOpenFilejButton4ActionPerformed
//        int id = Integer.parseInt(txtFolderID.getText());
//        EntityManagerFactory emf = Persistence.createEntityManagerFactory("slSystemPU");
//        EntityManager em = emf.createEntityManager();
//
//        Clientfolder clientfolder;
//
//        clientfolder = em.getReference(Clientfolder.class, id);
//        //clientfolder.getDoc1();
//
//        JFileChooser fr = new JFileChooser();
//        FileSystemView fw = fr.getFileSystemView();
//        System.out.println(fw.getDefaultDirectory());
//        String FilePathWithName=fw.getDefaultDirectory() + "\\client_" + id + "_04." + clientfolder.getMime4();
//
//        File outfile = null;
//        outfile = new File(FilePathWithName);
//
//        try
//        {
//            writeFile(outfile, clientfolder.getDoc4());
//        }
//        catch (IOException e)
//        {
//            System.out.println(e.getMessage());
//        }
//        try {
//            Runtime rt = Runtime.getRuntime();
//            rt.exec("cmd /c start " + ResolveWhiteSpace(FilePathWithName));
//
//        } catch (Exception e) {
//            System.out.println("Error opening file: " + e.getMessage());
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_EditOpenFilejButton4ActionPerformed

    private void jButtonBack2MainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBack2MainActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        MainWindowFrame frame = new MainWindowFrame();
        frame.setVisible(true);
        dispose();        
    }//GEN-LAST:event_jButtonBack2MainActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed

//        
//int id;
//
//
//     try { 
//        id=Integer.parseInt(txtFolderID.getText()); 
//    } catch(NumberFormatException e) { 
//       JOptionPane.showMessageDialog(null, "Not a valid carepack ID");
//       return;
//    }
//
//        try
//        {
//            EntityManagerFactory emf = Persistence.createEntityManagerFactory(
//                    "slSystemPU");
//            EntityManager em = emf.createEntityManager();
//
//            em.getTransaction().begin();
//
//            
//
//            Clientfolder cp = em.find(Clientfolder.class, id);
//      
//        
//            FileService load1 = new FileService();
//            FileService load2 = new FileService();
//            FileService load3 = new FileService();
//            FileService load4 = new FileService();
//            FileService load5 = new FileService();
//
//
//            File saveFile1 = new File(EditSelectedFileViewDoc1.getText());
//            
//            if (saveFile1.isFile())
//            {
//                cp.setDoc1(load1.readImageOldWay(saveFile1));
//                cp.setMime1(EditMimeType1.getText());
//            }
//
//            File saveFile2 = new File(EditSelectedFileViewDoc2.getText());
//            
//            if (saveFile2.isFile())
//            {
//                cp.setDoc2(load2.readImageOldWay(saveFile2));
//                cp.setMime2(EditMimeType2.getText());
//            }
//            
//            File saveFile3 = new File(EditSelectedFileViewDoc3.getText());
//            
//            if (saveFile3.isFile())
//            {
//                cp.setDoc3(load3.readImageOldWay(saveFile3));
//                cp.setMime3(EditMimeType3.getText());
//            }
//            File saveFile4 = new File(EditSelectedFileViewDoc4.getText());
//            
//            if (saveFile4.isFile())
//            {
//                cp.setDoc4(load4.readImageOldWay(saveFile4));
//                cp.setMime4(EditMimeType4.getText());
//            }
//            File saveFile5 = new File(EditSelectedFileViewDoc5.getText());
//            
//            if (saveFile5.isFile())
//            {
//                cp.setDoc5(load5.readImageOldWay(saveFile5));
//                cp.setMime5(EditMimeType5.getText());
//            }            
//
//            em.getTransaction().commit();
//            JOptionPane.showMessageDialog(null,
//                    "Client Folder " + FolderNamejTextField1.getText().toUpperCase() + " is updated successfully ");
//            em.close();
//            
//        txtFolderID.setText("");
//        FirstNamejTextField.setText("");
//        LastNamejTextField.setText("");
//        FolderNamejTextField1.setText("");
//        
//        EditSelectedFileViewDoc1.setText("");
//        EditSelectedFileViewDoc2.setText("");
//        EditSelectedFileViewDoc3.setText("");
//        EditSelectedFileViewDoc4.setText("");
//        EditSelectedFileViewDoc5.setText("");
//        EditMimeType1.setText("");
//        EditMimeType2.setText("");
//        EditMimeType3.setText("");
//        EditMimeType4.setText("");
//        EditMimeType5.setText("");            
//            
//
//        }
//        catch (IOException ex)
//        {
//            ex.printStackTrace();
//        }  
//          
        
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    
  
private void findbyId(Integer id) throws NonexistentEntityException
    {

        
//        EntityManagerFactory emf = Persistence.createEntityManagerFactory("slSystemPU");
//        EntityManager em = emf.createEntityManager();
//
//        
//        Clientfolder  cf;
//        try
//        {
//            cf = em.getReference(Clientfolder.class, id);
//
//            if (id < 1)
//            {
//                JOptionPane.showMessageDialog(this,
//                        "This is not a valid number ! \nNo Carepack found");
//            }
//        }
//        catch (EntityNotFoundException enfe)
//        {
//            throw new NonexistentEntityException(
//                    "The Carepack with id " + id + " no longer exists.", enfe);
//        }
//        
//
//
//        FolderNamejTextField1.setText(cf.getFolderName());   
//        EditSelectedFileViewDoc1.setText(cf.getDoc1()==null? "": String.valueOf(cf.getDoc1()));
//        EditSelectedFileViewDoc2.setText(cf.getDoc2()==null? "": String.valueOf(cf.getDoc2()));
//        EditSelectedFileViewDoc3.setText(cf.getDoc3()==null? "": String.valueOf(cf.getDoc3()));
//        EditSelectedFileViewDoc4.setText(cf.getDoc4()==null? "": String.valueOf(cf.getDoc4()));
//        EditSelectedFileViewDoc5.setText(cf.getDoc5()==null? "": String.valueOf(cf.getDoc5()));
//        EditMimeType1.setText(cf.getMime1());
//        EditMimeType2.setText(cf.getMime2());
//        EditMimeType3.setText(cf.getMime3());
//        EditMimeType4.setText(cf.getMime4());
//        EditMimeType5.setText(cf.getMime5());        
//
//        
////        FirstNamejTextField.setText(clientObj.getFirstName());
////        LastNamejTextField.setText(clientObj.getLastName()); 
////        
////        Clientfolder cf = em.getReference(Clientfolder.class, id);
////                
//        
//        em.close();
        
    }
    
    
    
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCarePackDocsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCarePackDocsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCarePackDocsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCarePackDocsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCarePackDocsFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditLocate1;
    private javax.swing.JButton EditLocate2;
    private javax.swing.JButton EditLocate3;
    private javax.swing.JButton EditLocate4;
    private javax.swing.JButton EditLocate5;
    private javax.swing.JTextField EditMimeType1;
    private javax.swing.JTextField EditMimeType2;
    private javax.swing.JTextField EditMimeType3;
    private javax.swing.JTextField EditMimeType4;
    private javax.swing.JTextField EditMimeType5;
    private javax.swing.JButton EditOpenFilejButton1;
    private javax.swing.JButton EditOpenFilejButton2;
    private javax.swing.JButton EditOpenFilejButton3;
    private javax.swing.JButton EditOpenFilejButton4;
    private javax.swing.JButton EditOpenFilejButton5;
    private javax.swing.JTextField EditSelectedFileViewDoc1;
    private javax.swing.JTextField EditSelectedFileViewDoc2;
    private javax.swing.JTextField EditSelectedFileViewDoc3;
    private javax.swing.JTextField EditSelectedFileViewDoc4;
    private javax.swing.JTextField EditSelectedFileViewDoc5;
    private javax.swing.JButton FindjButton;
    private javax.swing.JLabel FirstNamejLabel;
    private javax.swing.JTextField FirstNamejTextField;
    private javax.swing.JTextField FolderNamejTextField1;
    private javax.swing.JLabel LastNamejLabel;
    private javax.swing.JTextField LastNamejTextField;
    private javax.swing.JButton jButtonBack2Main;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtFolderID;
    // End of variables declaration//GEN-END:variables
}
