package HCI;

import Classes.Carepack;
import Classes.Client;
import control.exceptions.NonexistentEntityException;
import java.io.File;
import java.io.IOException;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import java.io.OutputStream;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityNotFoundException;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileSystemView;

/**
 * @author Joynal Abedin  20-Jun-2013
 */


public class ViewFolderFrame extends javax.swing.JFrame {

    /** Creates new form ViewFolderFrame */
    public ViewFolderFrame() {
        initComponents();
        
          setTitle("Simple Legal System                     View client's  here");
        initComponents();
        this.setIconImage(new ImageIcon("legal.gif").getImage());
        // centre the user interface on the screen
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((screenSize.width - getWidth()) / 2,
                (screenSize.height - getHeight()) / 2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        HeadingLabel = new javax.swing.JLabel();
        EditFolderButton = new javax.swing.JButton();
        DeleteFolderButton = new javax.swing.JButton();
        ViewFolderButton = new javax.swing.JButton();
        GobackButton = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        EditSelectedFileViewDoc1 = new javax.swing.JTextField();
        EditMimeType1 = new javax.swing.JTextField();
        EditOpenFilejButton1 = new javax.swing.JButton();
        EditLocate1 = new javax.swing.JButton();
        EditLocate2 = new javax.swing.JButton();
        EditOpenFilejButton2 = new javax.swing.JButton();
        EditMimeType2 = new javax.swing.JTextField();
        EditSelectedFileViewDoc2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        EditSelectedFileViewDoc3 = new javax.swing.JTextField();
        EditMimeType3 = new javax.swing.JTextField();
        EditOpenFilejButton3 = new javax.swing.JButton();
        EditLocate3 = new javax.swing.JButton();
        EditLocate4 = new javax.swing.JButton();
        EditOpenFilejButton4 = new javax.swing.JButton();
        EditMimeType4 = new javax.swing.JTextField();
        EditSelectedFileViewDoc4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        EditSelectedFileViewDoc5 = new javax.swing.JTextField();
        EditMimeType5 = new javax.swing.JTextField();
        EditOpenFilejButton5 = new javax.swing.JButton();
        EditLocate5 = new javax.swing.JButton();
        FirstNamejLabel = new javax.swing.JLabel();
        FirstNamejTextField = new javax.swing.JTextField();
        LastNamejLabel = new javax.swing.JLabel();
        LastNamejTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        FolderNamejTextField1 = new javax.swing.JTextField();
        txtFolderID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeadingLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HeadingLabel.setText("View or Edit and Delete a client folder here");

        EditFolderButton.setText("Edit this folder");
        EditFolderButton.setActionCommand("");

        DeleteFolderButton.setText("Delete this folder");

        ViewFolderButton.setText("View this folder");
        ViewFolderButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ViewFolderButtonActionPerformed(evt);
            }
        });

        GobackButton.setText("Go to main window");
        GobackButton.setActionCommand("");
        GobackButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                GobackButtonActionPerformed(evt);
            }
        });

        jLabel19.setText("Edit Doc 1");

        EditMimeType1.setEditable(false);

        EditOpenFilejButton1.setText("OpenFile");
        EditOpenFilejButton1.setActionCommand("");
        EditOpenFilejButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditOpenFilejButton1ActionPerformed(evt);
            }
        });

        EditLocate1.setText("Locate");
        EditLocate1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditLocate1ActionPerformed(evt);
            }
        });

        EditLocate2.setText("Locate");
        EditLocate2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditLocate2ActionPerformed(evt);
            }
        });

        EditOpenFilejButton2.setText("OpenFile");
        EditOpenFilejButton2.setActionCommand("");
        EditOpenFilejButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditOpenFilejButton2ActionPerformed(evt);
            }
        });

        EditMimeType2.setEditable(false);

        jLabel6.setText("Edit Doc 2");

        jLabel16.setText("Edit Doc 3");

        EditMimeType3.setEditable(false);

        EditOpenFilejButton3.setText("OpenFile");
        EditOpenFilejButton3.setActionCommand("");
        EditOpenFilejButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditOpenFilejButton3ActionPerformed(evt);
            }
        });

        EditLocate3.setText("Locate");
        EditLocate3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditLocate3ActionPerformed(evt);
            }
        });

        EditLocate4.setText("Lcoate");
        EditLocate4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditLocate4ActionPerformed(evt);
            }
        });

        EditOpenFilejButton4.setText("OpenFile");
        EditOpenFilejButton4.setActionCommand("");
        EditOpenFilejButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditOpenFilejButton4ActionPerformed(evt);
            }
        });

        EditMimeType4.setEditable(false);

        jLabel17.setText("Edit Doc 4");

        jLabel18.setText("Edit Doc 5");

        EditMimeType5.setEditable(false);

        EditOpenFilejButton5.setText("OpenFile");
        EditOpenFilejButton5.setActionCommand("");
        EditOpenFilejButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditOpenFilejButton5ActionPerformed(evt);
            }
        });

        EditLocate5.setText("Locate");
        EditLocate5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EditLocate5ActionPerformed(evt);
            }
        });

        FirstNamejLabel.setText("First Name");

        FirstNamejTextField.setEditable(false);
        FirstNamejTextField.setToolTipText("Enter a first name");
        FirstNamejTextField.setName("FirstName"); // NOI18N
        FirstNamejTextField.setPreferredSize(new java.awt.Dimension(100, 20));

        LastNamejLabel.setText("Last Name");

        LastNamejTextField.setEditable(false);

        jLabel1.setText("Enter folder name");

        FolderNamejTextField1.setEditable(false);
        FolderNamejTextField1.setToolTipText("Enter a folder name");

        txtFolderID.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel1))
                                    .addComponent(LastNamejLabel)
                                    .addComponent(FirstNamejLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstNamejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(LastNamejTextField)
                                    .addComponent(FolderNamejTextField1))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel19)
                                                    .addComponent(jLabel6)))
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel16))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EditSelectedFileViewDoc1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EditSelectedFileViewDoc2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EditSelectedFileViewDoc3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EditSelectedFileViewDoc4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EditMimeType1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EditMimeType2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EditMimeType3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EditMimeType4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(EditOpenFilejButton1))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(EditOpenFilejButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(EditOpenFilejButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(EditOpenFilejButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(EditLocate1)
                                                    .addComponent(EditLocate2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(EditLocate4)
                                                    .addComponent(EditLocate3))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(8, 8, 8)
                                        .addComponent(EditSelectedFileViewDoc5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EditMimeType5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EditOpenFilejButton5)
                                        .addGap(7, 7, 7)
                                        .addComponent(EditLocate5, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))))
                            .addComponent(EditFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GobackButton))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(HeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(185, 185, 185))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtFolderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(286, 286, 286))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ViewFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {DeleteFolderButton, EditFolderButton, GobackButton, ViewFolderButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeadingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFolderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EditOpenFilejButton1)
                        .addGap(3, 3, 3)
                        .addComponent(EditOpenFilejButton2)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EditOpenFilejButton3)
                            .addComponent(EditLocate3)
                            .addComponent(EditMimeType3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditSelectedFileViewDoc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EditMimeType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EditLocate1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(EditSelectedFileViewDoc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EditMimeType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(FirstNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(FirstNamejLabel))
                                                    .addComponent(EditSelectedFileViewDoc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EditLocate2))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(FolderNamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel17))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(EditSelectedFileViewDoc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EditMimeType4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EditOpenFilejButton4)
                                            .addComponent(EditLocate4))
                                        .addGap(4, 4, 4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(EditSelectedFileViewDoc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(EditMimeType5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EditOpenFilejButton5)
                                        .addComponent(EditLocate5))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LastNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LastNamejLabel))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(15, 15, 15)
                .addComponent(ViewFolderButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteFolderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GobackButton)
                .addGap(211, 211, 211))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {EditFolderButton, GobackButton, ViewFolderButton});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {EditSelectedFileViewDoc1, EditSelectedFileViewDoc2, EditSelectedFileViewDoc3, EditSelectedFileViewDoc4, EditSelectedFileViewDoc5});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GobackButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_GobackButtonActionPerformed
    {//GEN-HEADEREND:event_GobackButtonActionPerformed
        // TODO add your handling code here:
        MainWindowFrame frame = new MainWindowFrame();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_GobackButtonActionPerformed

    private void ViewFolderButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ViewFolderButtonActionPerformed
    {//GEN-HEADEREND:event_ViewFolderButtonActionPerformed
             
       
        try
        {
            // TODO add your handling code here: this is actually creating a folder to user home directory.
            createUserDir("TodaysFolder");
        }
        catch (IOException ex)
        {
            ex.printStackTrace();
        }
     
        
        /*
        File folder = new File("C:\\Users\\Joynal Abedin\\LegalFolder");
File[] listOfFiles = folder.listFiles();

for (File file : listOfFiles) {
    if (file.isFile()) {
        System.out.println(file.getName());
    }
}
  */      
        
    }//GEN-LAST:event_ViewFolderButtonActionPerformed


public void writeFile(File file, byte[] data) throws IOException
 {
   OutputStream fo = new FileOutputStream(file);
   fo.write(data);
   fo.flush();
   fo.close();
 }    
      
    private void EditOpenFilejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditOpenFilejButton1ActionPerformed
//        int id = Integer.parseInt(txtFolderID.getText());
//        EntityManagerFactory emf = Persistence.createEntityManagerFactory("slSystemPU");
//        EntityManager em = emf.createEntityManager();
//
//        Clientfolder clientfolder;
//
//        clientfolder = em.getReference(Clientfolder.class, id);
//        //clientfolder.getDoc1();
//
//        JFileChooser fr = new JFileChooser();
//        FileSystemView fw = fr.getFileSystemView();
//        System.out.println(fw.getDefaultDirectory());
//        String FilePathWithName=fw.getDefaultDirectory() + "\\client_" + id + "_01." + clientfolder.getMime1();
//
//        File outfile = null;
//        outfile = new File(FilePathWithName);
//
//        try
//        {
//            writeFile(outfile, clientfolder.getDoc1());
//        }
//        catch (IOException e)
//        {
//            System.out.println(e.getMessage());
//        }
//        try {
//            Runtime rt = Runtime.getRuntime();
//            rt.exec("cmd /c start " + FilePathWithName);
//
//        } catch (Exception e) {
//            System.out.println("Error opening file: " + e.getMessage());
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_EditOpenFilejButton1ActionPerformed

    
    
    private void EditLocate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditLocate1ActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        try {
            EditSelectedFileViewDoc1.setText(chooser.getSelectedFile().toString());
            EditMimeType1.setText(EditSelectedFileViewDoc1.getText().substring(EditSelectedFileViewDoc1.getText().lastIndexOf('.')+1));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_EditLocate1ActionPerformed

    private void EditLocate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditLocate2ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        try {
            EditSelectedFileViewDoc2.setText(chooser.getSelectedFile().toString());
            EditMimeType2.setText(EditSelectedFileViewDoc2.getText().substring(EditSelectedFileViewDoc2.getText().lastIndexOf('.')+1));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_EditLocate2ActionPerformed

    private void EditOpenFilejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditOpenFilejButton2ActionPerformed
//        int id = Integer.parseInt(txtFolderID.getText());
//        EntityManagerFactory emf = Persistence.createEntityManagerFactory("slSystemPU");
//        EntityManager em = emf.createEntityManager();
//
//        Clientfolder clientfolder;
//
//        clientfolder = em.getReference(Clientfolder.class, id);
//        //clientfolder.getDoc1();
//
//        JFileChooser fr = new JFileChooser();
//        FileSystemView fw = fr.getFileSystemView();
//        System.out.println(fw.getDefaultDirectory());
//        String FilePathWithName=fw.getDefaultDirectory() + "\\client_" + id + "_02." + clientfolder.getMime2();
//
//        File outfile = null;
//        outfile = new File(FilePathWithName);
//
//        try
//        {
//            writeFile(outfile, clientfolder.getDoc2());
//        }
//        catch (IOException e)
//        {
//            System.out.println(e.getMessage());
//        }
//        try {
//            Runtime rt = Runtime.getRuntime();
//            rt.exec("cmd /c start " + FilePathWithName);
//
//        } catch (Exception e) {
//            System.out.println("Error opening file: " + e.getMessage());
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_EditOpenFilejButton2ActionPerformed

    private void EditOpenFilejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditOpenFilejButton3ActionPerformed
//        int id = Integer.parseInt(txtFolderID.getText());
//        EntityManagerFactory emf = Persistence.createEntityManagerFactory("slSystemPU");
//        EntityManager em = emf.createEntityManager();
//
//        Clientfolder clientfolder;
//
//        clientfolder = em.getReference(Clientfolder.class, id);
//        //clientfolder.getDoc1();
//
//        JFileChooser fr = new JFileChooser();
//        FileSystemView fw = fr.getFileSystemView();
//        System.out.println(fw.getDefaultDirectory());
//        String FilePathWithName=fw.getDefaultDirectory() + "\\client_" + id + "_03." + clientfolder.getMime3();
//
//        File outfile = null;
//        outfile = new File(FilePathWithName);
//
//        try
//        {
//            writeFile(outfile, clientfolder.getDoc3());
//        }
//        catch (IOException e)
//        {
//            System.out.println(e.getMessage());
//        }
//        try {
//            Runtime rt = Runtime.getRuntime();
//            rt.exec("cmd /c start " + FilePathWithName);
//
//        } catch (Exception e) {
//            System.out.println("Error opening file: " + e.getMessage());
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_EditOpenFilejButton3ActionPerformed

    private void EditLocate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditLocate3ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        try {
            EditSelectedFileViewDoc3.setText(chooser.getSelectedFile().toString());
            EditMimeType3.setText(EditSelectedFileViewDoc3.getText().substring(EditSelectedFileViewDoc3.getText().lastIndexOf('.')+1));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_EditLocate3ActionPerformed

    private void EditLocate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditLocate4ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        try {
            EditSelectedFileViewDoc4.setText(chooser.getSelectedFile().toString());
            EditMimeType4.setText(EditSelectedFileViewDoc4.getText().substring(EditSelectedFileViewDoc4.getText().lastIndexOf('.')+1));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_EditLocate4ActionPerformed

    private void EditOpenFilejButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditOpenFilejButton4ActionPerformed
//        int id = Integer.parseInt(txtFolderID.getText());
//        EntityManagerFactory emf = Persistence.createEntityManagerFactory("slSystemPU");
//        EntityManager em = emf.createEntityManager();
//
//        Clientfolder clientfolder;
//
//        clientfolder = em.getReference(Clientfolder.class, id);
//        //clientfolder.getDoc1();
//
//        JFileChooser fr = new JFileChooser();
//        FileSystemView fw = fr.getFileSystemView();
//        System.out.println(fw.getDefaultDirectory());
//        String FilePathWithName=fw.getDefaultDirectory() + "\\client_" + id + "_04." + clientfolder.getMime4();
//
//        File outfile = null;
//        outfile = new File(FilePathWithName);
//
//        try
//        {
//            writeFile(outfile, clientfolder.getDoc4());
//        }
//        catch (IOException e)
//        {
//            System.out.println(e.getMessage());
//        }
//        try {
//            Runtime rt = Runtime.getRuntime();
//            rt.exec("cmd /c start " + FilePathWithName);
//
//        } catch (Exception e) {
//            System.out.println("Error opening file: " + e.getMessage());
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_EditOpenFilejButton4ActionPerformed

    private void EditOpenFilejButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditOpenFilejButton5ActionPerformed
//        int id = Integer.parseInt(txtFolderID.getText());
//        EntityManagerFactory emf = Persistence.createEntityManagerFactory("slSystemPU");
//        EntityManager em = emf.createEntityManager();
//
//        Clientfolder clientfolder;
//
//        clientfolder = em.getReference(Clientfolder.class, id);
//        //clientfolder.getDoc1();
//
//        JFileChooser fr = new JFileChooser();
//        FileSystemView fw = fr.getFileSystemView();
//        System.out.println(fw.getDefaultDirectory());
//        String FilePathWithName=fw.getDefaultDirectory() + "\\client_" + id + "_05." + clientfolder.getMime5();
//
//        File outfile = null;
//        outfile = new File(FilePathWithName);
//
//        try
//        {
//            writeFile(outfile, clientfolder.getDoc5());
//        }
//        catch (IOException e)
//        {
//            //Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, e);
//        }
//        try {
//            Runtime rt = Runtime.getRuntime();
//            rt.exec("cmd /c start " + FilePathWithName);
//
//        } catch (Exception e) {
//            System.out.println("Error opening file: " + e.getMessage());
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_EditOpenFilejButton5ActionPerformed

    private void EditLocate5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditLocate5ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        try {
            EditSelectedFileViewDoc5.setText(chooser.getSelectedFile().toString());
            EditMimeType5.setText(EditSelectedFileViewDoc5.getText().substring(EditSelectedFileViewDoc5.getText().lastIndexOf('.')+1));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_EditLocate5ActionPerformed

    
private void findbyId(Integer id) throws NonexistentEntityException
    {

        
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("slSystemPU");
        EntityManager em = emf.createEntityManager();

        
        Carepack  cf;
        try
        {
            cf = em.getReference(Carepack.class, id);

            if (id < 1)
            {
                JOptionPane.showMessageDialog(this,
                        "This is not a valid number ! \nNo Carepack found");
            }
        }
        catch (EntityNotFoundException enfe)
        {
            throw new NonexistentEntityException(
                    "The Carepack with id " + id + " no longer exists.", enfe);
        }
        

System.out.println(cf.getDescription());
//        FolderNamejTextField1.setText(cf.getFolderName());   
//        EditSelectedFileViewDoc1.setText(cf.getDoc1()==null? "": String.valueOf(cf.getDoc1()));
//        EditSelectedFileViewDoc2.setText(cf.getDoc2()==null? "": String.valueOf(cf.getDoc2()));
//        EditSelectedFileViewDoc3.setText(cf.getDoc3()==null? "": String.valueOf(cf.getDoc3()));
//        EditSelectedFileViewDoc4.setText(cf.getDoc4()==null? "": String.valueOf(cf.getDoc4()));
//        EditSelectedFileViewDoc5.setText(cf.getDoc5()==null? "": String.valueOf(cf.getDoc5()));
//        EditMimeType1.setText(cf.getMime1());
//        EditMimeType2.setText(cf.getMime2());
//        EditMimeType3.setText(cf.getMime3());
//        EditMimeType4.setText(cf.getMime4());
//        EditMimeType5.setText(cf.getMime5());        

        
//        FirstNamejTextField.setText(clientObj.getFirstName());
//        LastNamejTextField.setText(clientObj.getLastName()); 
//        
//        Clientfolder cf = em.getReference(Clientfolder.class, id);
//                
        
        em.close();
        
    }
    
    
    
    
    
    private void createUserDir(final String dirName) throws IOException {
    final File homeDir = new File(System.getProperty("user.home"));
    final File dir = new File(homeDir, dirName);
    if (dir.exists() && !dir.mkdirs()) {
        JOptionPane.showMessageDialog(this, "A folder exixts with the name of "+dirName.toUpperCase()+ " therefore unable to create!");
        throw new IOException("Unable to create " + dir.getAbsolutePath());
        
    }
    else{
        JOptionPane.showMessageDialog(this, "New folder has been created");
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFolderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFolderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFolderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFolderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFolderFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteFolderButton;
    private javax.swing.JButton EditFolderButton;
    private javax.swing.JButton EditLocate1;
    private javax.swing.JButton EditLocate2;
    private javax.swing.JButton EditLocate3;
    private javax.swing.JButton EditLocate4;
    private javax.swing.JButton EditLocate5;
    private javax.swing.JTextField EditMimeType1;
    private javax.swing.JTextField EditMimeType2;
    private javax.swing.JTextField EditMimeType3;
    private javax.swing.JTextField EditMimeType4;
    private javax.swing.JTextField EditMimeType5;
    private javax.swing.JButton EditOpenFilejButton1;
    private javax.swing.JButton EditOpenFilejButton2;
    private javax.swing.JButton EditOpenFilejButton3;
    private javax.swing.JButton EditOpenFilejButton4;
    private javax.swing.JButton EditOpenFilejButton5;
    private javax.swing.JTextField EditSelectedFileViewDoc1;
    private javax.swing.JTextField EditSelectedFileViewDoc2;
    private javax.swing.JTextField EditSelectedFileViewDoc3;
    private javax.swing.JTextField EditSelectedFileViewDoc4;
    private javax.swing.JTextField EditSelectedFileViewDoc5;
    private javax.swing.JLabel FirstNamejLabel;
    private javax.swing.JTextField FirstNamejTextField;
    private javax.swing.JTextField FolderNamejTextField1;
    private javax.swing.JButton GobackButton;
    private javax.swing.JLabel HeadingLabel;
    private javax.swing.JLabel LastNamejLabel;
    private javax.swing.JTextField LastNamejTextField;
    private javax.swing.JButton ViewFolderButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtFolderID;
    // End of variables declaration//GEN-END:variables

}
